using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class CallConnection : Structure
    {

        public partial class callConnection : CallConnection
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "callConnection";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("id")]
                public string id_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("ip")]
                public string ip_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("ipv6")]
                public string ipv6_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("port")]
                public int? port_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("peer_tag")]
                public byte[] peer_tag_;

        }

    }

}
