using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class ChatAction : Structure
    {

        public partial class chatActionUploadingVideoNote : ChatAction
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "chatActionUploadingVideoNote";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("progress")]
                public int? progress_;

        }

    }

}
