using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class MaskPosition : Structure
    {

        public partial class maskPosition : MaskPosition
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "maskPosition";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("point")]
                public MaskPoint point_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("x_shift")]
                public double? x_shift_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("y_shift")]
                public double? y_shift_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("scale")]
                public double? scale_;

        }

    }

}
