using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class MessageContent : Structure
    {

        public partial class messageChatAddMembers : MessageContent
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "messageChatAddMembers";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("member_user_ids")]
                public int[] member_user_ids_;

        }

    }

}
