using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class MessageContent : Structure
    {

        public partial class messageSupergroupChatCreate : MessageContent
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "messageSupergroupChatCreate";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("title")]
                public string title_;

        }

    }

}
