using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class PageBlock : Structure
    {

        public partial class pageBlockAudio : PageBlock
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "pageBlockAudio";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("audio")]
                public Audio.audio audio_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("caption")]
                public RichText caption_;

        }

    }

}
