using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class PasswordRecoveryInfo : Structure
    {

        public partial class passwordRecoveryInfo : PasswordRecoveryInfo
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "passwordRecoveryInfo";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("recovery_email_address_pattern")]
                public string recovery_email_address_pattern_;

        }

    }

}
