using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class PaymentForm : Structure
    {

        public partial class paymentForm : PaymentForm
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "paymentForm";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("invoice")]
                public Invoice.invoice invoice_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("url")]
                public string url_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("payments_provider")]
                public PaymentsProviderStripe.paymentsProviderStripe payments_provider_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("saved_order_info")]
                public OrderInfo.orderInfo saved_order_info_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("saved_credentials")]
                public SavedCredentials.savedCredentials saved_credentials_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("can_save_credentials")]
                public bool can_save_credentials_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("need_password")]
                public bool need_password_;

        }

    }

}
