using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class SecretChat : Structure
    {

        public partial class secretChat : SecretChat
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "secretChat";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("id")]
                public int id_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("user_id")]
                public int user_id_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("state")]
                public SecretChatState state_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_outbound")]
                public bool is_outbound_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("ttl")]
                public int ttl_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("key_hash")]
                public byte[] key_hash_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("layer")]
                public int layer_;

        }

    }

}
