using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class ShippingOption : Structure
    {

        public partial class shippingOption : ShippingOption
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "shippingOption";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("id")]
                public string id_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("title")]
                public string title_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("price_parts")]
                public LabeledPricePart.labeledPricePart[] price_parts_;

        }

    }

}
