using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TestVectorStringObject : Structure
    {

        public partial class testVectorStringObject : TestVectorStringObject
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "testVectorStringObject";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("value")]
                public TestString.testString[] value_;

        }

    }

}
