using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Update : Structure
    {

        public partial class updateChatLastMessage : Update
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "updateChatLastMessage";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("chat_id")]
                public long chat_id_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("last_message")]
                public Message.message last_message_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("order")]
                public string order_;

        }

    }

}
