using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class UserPrivacySettingRule : Structure
    {

        public partial class userPrivacySettingRuleAllowContacts : UserPrivacySettingRule
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "userPrivacySettingRuleAllowContacts";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

        }

    }

}
