using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Contains information about the period of inactivity after which the current user's account will automatically be deleted
        /// </summary>
        public partial class AccountTtl : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "accountTtl";

            /// <summary>
            /// Extra data attached to the object
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Number of days of inactivity before the account will be flagged for deletion; 30-366 days
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("days")]
            public int Days { get; set; }
        }
    }
}
// REUSE-IgnoreEnd