using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Contains information about an affiliate that received commission from a Telegram Star transaction
        /// </summary>
        public partial class AffiliateInfo : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "affiliateInfo";

            /// <summary>
            /// Extra data attached to the object
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// The number of Telegram Stars received by the affiliate for each 1000 Telegram Stars received by the program owner
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("commission_per_mille")]
            public int CommissionPerMille { get; set; }

            /// <summary>
            /// Identifier of the chat which received the commission
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("affiliate_chat_id")]
            public long AffiliateChatId { get; set; }

            /// <summary>
            /// The amount of Telegram Stars that were received by the affiliate; can be negative for refunds
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("star_amount")]
            public StarAmount StarAmount { get; set; }
        }
    }
}
// REUSE-IgnoreEnd