using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
namespace TdLib.TdApi.Objects;
public partial class AffiliateType : Object
{
    /// <summary>
    /// The affiliate is a bot owned by the current user
    /// </summary>
    public class AffiliateTypeBot : AffiliateType
    {
        /// <summary>
        /// Data type for serialization
        /// </summary>
        [JsonProperty("@type")]
        public override string DataType { get; set; } = "affiliateTypeBot";

        /// <summary>
        /// Extra data attached to the message
        /// </summary>
        [JsonProperty("@extra")]
        public override string Extra { get; set; }

                /// <summary>
                /// User identifier of the bot
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("user_id")]
                public long UserId { get; set; }
    }
}
// REUSE-IgnoreEnd