using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class AuthenticationCodeType : Object
        {
            /// <summary>
            /// Provides information about the method by which an authentication code is delivered to the user
            /// </summary>
            public class AuthenticationCodeTypeTelegramMessage : AuthenticationCodeType
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "authenticationCodeTypeTelegramMessage";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Length of the code
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("length")]
                public int Length { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd