using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class CanSendMessageToUserResult : Object
        {
            /// <summary>
            /// The user can't be messaged, because they restrict new chats with non-contacts
            /// </summary>
            public class CanSendMessageToUserResultUserRestrictsNewChats : CanSendMessageToUserResult
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "canSendMessageToUserResultUserRestrictsNewChats";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }


            }
        }
    }
}
// REUSE-IgnoreEnd