using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
namespace TdLib.TdApi.Objects;
public partial class ChatMembersFilter : Object
{
    /// <summary>
    /// Returns the owner and administrators
    /// </summary>
    public class ChatMembersFilterAdministrators : ChatMembersFilter
    {
        /// <summary>
        /// Data type for serialization
        /// </summary>
        [JsonProperty("@type")]
        public override string DataType { get; set; } = "chatMembersFilterAdministrators";

        /// <summary>
        /// Extra data attached to the message
        /// </summary>
        [JsonProperty("@extra")]
        public override string Extra { get; set; }


    }
}
// REUSE-IgnoreEnd