using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class ChatEventAction : Object
        {
            /// <summary>
            /// A new member joined the chat via an invite link
            /// </summary>
            public class ChatEventMemberJoinedByInviteLink : ChatEventAction
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "chatEventMemberJoinedByInviteLink";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Invite link used to join the chat
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("invite_link")]
                public ChatInviteLink InviteLink { get; set; }

                /// <summary>
                /// True, if the user has joined the chat using an invite link for a chat folder
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("via_chat_folder_invite_link")]
                public bool ViaChatFolderInviteLink { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd