using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class ChatTheme : Object
        {
            /// <summary>
            /// A chat theme based on an upgraded gift
            /// </summary>
            public class ChatThemeGift : ChatTheme
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "chatThemeGift";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// The chat theme
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("gift_theme")]
                public GiftChatTheme GiftTheme { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd