using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Describes actions that a user is allowed to take in a chat
        /// </summary>
        public partial class ChatPermissions : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "chatPermissions";

            /// <summary>
            /// Extra data attached to the object
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// True, if the user can send text messages, contacts, giveaways, giveaway winners, invoices, locations, and venues
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_send_basic_messages")]
            public bool CanSendBasicMessages { get; set; }

            /// <summary>
            /// True, if the user can send music files
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_send_audios")]
            public bool CanSendAudios { get; set; }

            /// <summary>
            /// True, if the user can send documents
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_send_documents")]
            public bool CanSendDocuments { get; set; }

            /// <summary>
            /// True, if the user can send photos
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_send_photos")]
            public bool CanSendPhotos { get; set; }

            /// <summary>
            /// True, if the user can send videos
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_send_videos")]
            public bool CanSendVideos { get; set; }

            /// <summary>
            /// True, if the user can send video notes
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_send_video_notes")]
            public bool CanSendVideoNotes { get; set; }

            /// <summary>
            /// True, if the user can send voice notes
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_send_voice_notes")]
            public bool CanSendVoiceNotes { get; set; }

            /// <summary>
            /// True, if the user can send polls
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_send_polls")]
            public bool CanSendPolls { get; set; }

            /// <summary>
            /// True, if the user can send animations, games, stickers, and dice and use inline bots
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_send_other_messages")]
            public bool CanSendOtherMessages { get; set; }

            /// <summary>
            /// True, if the user may add a web page preview to their messages
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_add_web_page_previews")]
            public bool CanAddWebPagePreviews { get; set; }

            /// <summary>
            /// True, if the user can change the chat title, photo, and other settings
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_change_info")]
            public bool CanChangeInfo { get; set; }

            /// <summary>
            /// True, if the user can invite new users to the chat
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_invite_users")]
            public bool CanInviteUsers { get; set; }

            /// <summary>
            /// True, if the user can pin messages
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_pin_messages")]
            public bool CanPinMessages { get; set; }

            /// <summary>
            /// True, if the user can create topics
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_create_topics")]
            public bool CanCreateTopics { get; set; }
        }
    }
}
// REUSE-IgnoreEnd