using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TdApi
    {
        public class ChatReportSpamState : Object
        {
            [JsonProperty("@type")] public override string DataType { get; set; } = "chatReportSpamState";

            [JsonProperty("@extra")] public override string Extra { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_report_spam")]
            public bool CanReportSpam { get; set; }
        }
    }
}