using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class ChatEventAction : Object
        {
            /// <summary>
            /// A new forum topic was created
            /// </summary>
            public class ChatEventForumTopicCreated : ChatEventAction
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "chatEventForumTopicCreated";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Information about the topic
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("topic_info")]
                public ForumTopicInfo TopicInfo { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd