using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
namespace TdLib.TdApi.Objects;
public partial class ChatAction : Object
{
    /// <summary>
    /// The user is uploading a voice note
    /// </summary>
    public class ChatActionUploadingVoiceNote : ChatAction
    {
        /// <summary>
        /// Data type for serialization
        /// </summary>
        [JsonProperty("@type")]
        public override string DataType { get; set; } = "chatActionUploadingVoiceNote";

        /// <summary>
        /// Extra data attached to the message
        /// </summary>
        [JsonProperty("@extra")]
        public override string Extra { get; set; }

                /// <summary>
                /// Upload progress, as a percentage
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("progress")]
                public int Progress { get; set; }
    }
}
// REUSE-IgnoreEnd