using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class ChatEventAction : Object
        {
            /// <summary>
            /// The has_automatic_translation setting of a channel was toggled
            /// </summary>
            public class ChatEventAutomaticTranslationToggled : ChatEventAction
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "chatEventAutomaticTranslationToggled";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// New value of has_automatic_translation
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("has_automatic_translation")]
                public bool HasAutomaticTranslation { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd