using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Describes a user that had or will have a birthday soon
        /// </summary>
        public partial class CloseBirthdayUser : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "closeBirthdayUser";

            /// <summary>
            /// Extra data attached to the object
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// User identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("user_id")]
            public long UserId { get; set; }

            /// <summary>
            /// Birthdate of the user
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("birthdate")]
            public Birthdate Birthdate { get; set; }
        }
    }
}
// REUSE-IgnoreEnd