using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class CollectibleItemType : Object
        {
            /// <summary>
            /// A phone number
            /// </summary>
            public class CollectibleItemTypePhoneNumber : CollectibleItemType
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "collectibleItemTypePhoneNumber";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// The phone number
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("phone_number")]
                public string PhoneNumber { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd