using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Describes actions that a user is allowed to take in a community
        /// </summary>
        public partial class CommunityPermissions : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "communityPermissions";

            /// <summary>
            /// Extra data attached to the object
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// True, if the user can change the chats added to the community
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_edit_chat_list")]
            public bool CanEditChatList { get; set; }
        }
    }
}
// REUSE-IgnoreEnd