using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TdApi
    {
        public partial class DeviceToken : Object
        {
            public class DeviceTokenApplePushVoIP : DeviceToken
            {
                [JsonProperty("@type")] public override string DataType { get; set; } = "deviceTokenApplePushVoIP";

                [JsonProperty("@extra")] public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("device_token")]
                public string DeviceToken { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_app_sandbox")]
                public bool IsAppSandbox { get; set; }
            }
        }
    }
}