using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
namespace TdLib.TdApi.Objects;
public partial class DeviceToken : Object
{
    /// <summary>
    /// A token for Ubuntu Push Client service
    /// </summary>
    public class DeviceTokenUbuntuPush : DeviceToken
    {
        /// <summary>
        /// Data type for serialization
        /// </summary>
        [JsonProperty("@type")]
        public override string DataType { get; set; } = "deviceTokenUbuntuPush";

        /// <summary>
        /// Extra data attached to the message
        /// </summary>
        [JsonProperty("@extra")]
        public override string Extra { get; set; }

                /// <summary>
                /// Token; may be empty to deregister a device
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("token")]
                public string Token { get; set; }
    }
}
// REUSE-IgnoreEnd