using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class DeviceToken : Object
        {
            /// <summary>
            /// A token for Windows Push Notification Services
            /// </summary>
            public class DeviceTokenWindowsPush : DeviceToken
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "deviceTokenWindowsPush";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// The access token that will be used to send notifications; may be empty to deregister a device
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("access_token")]
                public string AccessToken { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd