using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Represents a gift that was acquired by the current user on an auction
        /// </summary>
        public partial class GiftAuctionAcquiredGift : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "giftAuctionAcquiredGift";

            /// <summary>
            /// Extra data attached to the object
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Receiver of the gift
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("receiver_id")]
            public MessageSender ReceiverId { get; set; }

            /// <summary>
            /// Point in time (Unix timestamp) when the gift was acquired
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("date")]
            public int Date { get; set; }

            /// <summary>
            /// The number of Telegram Stars that were paid for the gift
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("star_count")]
            public long StarCount { get; set; }

            /// <summary>
            /// Identifier of the auction round in which the gift was acquired
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("auction_round_number")]
            public int AuctionRoundNumber { get; set; }

            /// <summary>
            /// Position of the user in the round among all auction participants
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("auction_round_position")]
            public int AuctionRoundPosition { get; set; }

            /// <summary>
            /// Message added to the gift
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("text")]
            public FormattedText Text { get; set; }

            /// <summary>
            /// True, if the sender and gift text are shown only to the gift receiver; otherwise, everyone will be able to see them
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("is_private")]
            public bool IsPrivate { get; set; }
        }
    }
}
// REUSE-IgnoreEnd