using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class InputPollType : Object
        {
            /// <summary>
            /// Describes the type of poll to send
            /// </summary>
            public class InputPollTypeRegular : InputPollType
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "inputPollTypeRegular";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// True, if answer options can be added to the poll after creation; not supported in channel chats and for anonymous polls
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("allow_adding_options")]
                public bool AllowAddingOptions { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd