using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// One of the files containing the translation of the document contains an error. The error is considered resolved when the file with the translation changes 
        /// </summary>
        public partial class InputPassportElementErrorSource : Object
        {
            /// <summary>
            /// One of the files containing the translation of the document contains an error. The error is considered resolved when the file with the translation changes 
            /// </summary>
            public class InputPassportElementErrorSourceTranslationFile : InputPassportElementErrorSource
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "inputPassportElementErrorSourceTranslationFile";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Current hash of the file containing the translation
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("file_hash")]
                public byte[] FileHash { get; set; }
            }
        }
    }
}