using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class InternalLinkType : Object
        {
            /// <summary>
            /// The link is a link to application settings
            /// </summary>
            public class InternalLinkTypeSettings : InternalLinkType
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "internalLinkTypeSettings";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Section of the application settings to open; may be null if none
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("section")]
                public SettingsSection Section { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd