using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class InternalLinkType : Object
        {
            /// <summary>
            /// The link is a link to a live story. Call searchPublicChat with the given chat username, then getChatActiveStories to get active stories in the chat,
            /// then find a live story among active stories of the chat, and then joinLiveStory to join the live story
            /// </summary>
            public class InternalLinkTypeLiveStory : InternalLinkType
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "internalLinkTypeLiveStory";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Username of the poster of the story
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("story_poster_username")]
                public string StoryPosterUsername { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd