using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class InternalLinkType : Object
        {
            /// <summary>
            /// The link is a link to a video chat. Call searchPublicChat with the given chat username, and then joinGroupCall with the given invite hash to process the link
            /// </summary>
            public class InternalLinkTypeVideoChat : InternalLinkType
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "internalLinkTypeVideoChat";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Username of the chat with the video chat
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("chat_username")]
                public string ChatUsername { get; set; }

                /// <summary>
                /// If non-empty, invite hash to be used to join the video chat without being muted by administrators
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("invite_hash")]
                public string InviteHash { get; set; }

                /// <summary>
                /// True, if the video chat is expected to be a live stream in a channel or a broadcast group
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_live_stream")]
                public bool IsLiveStream { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd