using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class LanguagePackStringValue : Object
        {
            /// <summary>
            /// Represents the value of a string in a language pack
            /// </summary>
            public class LanguagePackStringValueOrdinary : LanguagePackStringValue
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "languagePackStringValueOrdinary";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// String value
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("value")]
                public string Value { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd