using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TdApi
    {
        public class LanguagePackString : Object
        {
            [JsonProperty("@type")] public override string DataType { get; set; } = "languagePackString";

            [JsonProperty("@extra")] public override string Extra { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("key")]
            public string Key { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("value")]
            public LanguagePackStringValue Value { get; set; }
        }
    }
}