using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TdApi
    {
        public class LocalizationTargetInfo : Object
        {
            [JsonProperty("@type")] public override string DataType { get; set; } = "localizationTargetInfo";

            [JsonProperty("@extra")] public override string Extra { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("language_packs")]
            public LanguagePackInfo[] LanguagePacks { get; set; }
        }
    }
}