using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

namespace TdLib.TdApi.Objects;

/// <summary>
/// Contains a TDLib internal log verbosity level
/// </summary>
public partial class LogVerbosityLevel : Object
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "logVerbosityLevel";

    /// <summary>
    /// Extra data attached to the object
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Log verbosity level
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("verbosity_level")]
            public int VerbosityLevel { get; set; }
}
// REUSE-IgnoreEnd