using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class MessageContent : Object
        {
            /// <summary>
            /// A suggested post was approved
            /// </summary>
            public class MessageSuggestedPostApproved : MessageContent
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "messageSuggestedPostApproved";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Identifier of the message with the suggested post; can be 0 if the message was deleted
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("suggested_post_message_id")]
                public long SuggestedPostMessageId { get; set; }

                /// <summary>
                /// Price of the suggested post; may be null if the post is non-paid
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("price")]
                public SuggestedPostPrice Price { get; set; }

                /// <summary>
                /// Point in time (Unix timestamp) when the post is expected to be published
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("send_date")]
                public int SendDate { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd