using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TdApi
    {
        public partial class MessageContent : Object
        {
            public class MessageChatAddMembers : MessageContent
            {
                [JsonProperty("@type")] public override string DataType { get; set; } = "messageChatAddMembers";

                [JsonProperty("@extra")] public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("member_user_ids")]
                public int[] MemberUserIds { get; set; }
            }
        }
    }
}