using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Contains a list of reactions added to a message
        /// </summary>
        public partial class MessageReactions : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "messageReactions";

            /// <summary>
            /// Extra data attached to the object
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// List of added reactions
            /// </summary>
            [JsonProperty("reactions", ItemConverterType = typeof(Converter))]
            public MessageReaction[] Reactions { get; set; }

            /// <summary>
            /// True, if the reactions are tags and Telegram Premium users can filter messages by them
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("are_tags")]
            public bool AreTags { get; set; }
        }
    }
}
// REUSE-IgnoreEnd