using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class MessageSendingState : Object
        {
            /// <summary>
            /// The message failed to be sent
            /// </summary>
            public class MessageSendingStateFailed : MessageSendingState
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "messageSendingStateFailed";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// The cause of the message sending failure
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("error")]
                public Error Error { get; set; }

                /// <summary>
                /// True, if the message can be re-sent
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("can_retry")]
                public bool CanRetry { get; set; }

                /// <summary>
                /// True, if the message can be re-sent only on behalf of a different sender
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("need_another_sender")]
                public bool NeedAnotherSender { get; set; }

                /// <summary>
                /// True, if the message can be re-sent only if another quote is chosen in the message that is replied by the given message
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("need_another_reply_quote")]
                public bool NeedAnotherReplyQuote { get; set; }

                /// <summary>
                /// True, if the message can be re-sent only if the message to be replied is removed. This will be done automatically by resendMessages
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("need_drop_reply")]
                public bool NeedDropReply { get; set; }

                /// <summary>
                /// Time left before the message can be re-sent, in seconds. No update is sent when this field changes
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("retry_after")]
                public double? RetryAfter { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd