using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Contains privacy settings for chats with non-contacts
        /// </summary>
        public partial class NewChatPrivacySettings : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "newChatPrivacySettings";

            /// <summary>
            /// Extra data attached to the object
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// True, if non-contacts users are able to write first to the current user. Telegram Premium subscribers are able to write first regardless of this setting
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("allow_new_chats_from_unknown_users")]
            public bool AllowNewChatsFromUnknownUsers { get; set; }

            /// <summary>
            /// Number of Telegram Stars that must be paid for every incoming private message by non-contacts; 0-getOption("paid_message_star_count_max").
            /// If positive, then allow_new_chats_from_unknown_users must be true. The current user will receive getOption("paid_message_earnings_per_mille") Telegram Stars for each 1000 Telegram Stars paid for message sending.
            /// Can be positive, only if getOption("can_enable_paid_messages") is true
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("incoming_paid_message_star_count")]
            public long IncomingPaidMessageStarCount { get; set; }
        }
    }
}
// REUSE-IgnoreEnd