using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// One of the data fields contains an error. The error will be considered resolved when the value of the field changes 
        /// </summary>
        public partial class PassportElementErrorSource : Object
        {
            /// <summary>
            /// One of the data fields contains an error. The error will be considered resolved when the value of the field changes 
            /// </summary>
            public class PassportElementErrorSourceDataField : PassportElementErrorSource
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "passportElementErrorSourceDataField";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Field name
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("field_name")]
                public string FieldName { get; set; }
            }
        }
    }
}