using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TdApi
    {
        public class Proxy : Object
        {
            [JsonProperty("@type")] public override string DataType { get; set; } = "proxy";

            [JsonProperty("@extra")] public override string Extra { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("id")]
            public int Id { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("server")]
            public string Server { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("port")]
            public int Port { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("last_used_date")]
            public int LastUsedDate { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("is_enabled")]
            public bool IsEnabled { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("type")]
            public ProxyType Type { get; set; }
        }
    }
}