using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class PushMessageContent : Object
        {
            /// <summary>
            /// A message with a gift
            /// </summary>
            public class PushMessageContentGift : PushMessageContent
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "pushMessageContentGift";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Number of Telegram Stars that sender paid for the gift
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("star_count")]
                public long StarCount { get; set; }

                /// <summary>
                /// True, if the message is about prepaid upgrade of the gift by another user instead of actual receiving of a new gift
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_prepaid_upgrade")]
                public bool IsPrepaidUpgrade { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd