using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class ReactionType : Object
        {
            /// <summary>
            /// Describes type of message reaction
            /// </summary>
            public class ReactionTypeEmoji : ReactionType
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "reactionTypeEmoji";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Text representation of the reaction
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("emoji")]
                public string Emoji { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd