using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Contains information about restrictions that must be applied to a chat or a message
        /// </summary>
        public partial class RestrictionInfo : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "restrictionInfo";

            /// <summary>
            /// Extra data attached to the object
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// A human-readable description of the reason why access to the content must be restricted. If empty, then the content can be accessed,
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("restriction_reason")]
            public string RestrictionReason { get; set; }

            /// <summary>
            /// True, if media content of the messages must be hidden with 18+ spoiler.
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("has_sensitive_content")]
            public bool HasSensitiveContent { get; set; }
        }
    }
}
// REUSE-IgnoreEnd