using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
namespace TdLib.TdApi.Objects;
public partial class SearchMessagesFilter : Object
{
    /// <summary>
    /// Returns only photo messages
    /// </summary>
    public class SearchMessagesFilterPhoto : SearchMessagesFilter
    {
        /// <summary>
        /// Data type for serialization
        /// </summary>
        [JsonProperty("@type")]
        public override string DataType { get; set; } = "searchMessagesFilterPhoto";

        /// <summary>
        /// Extra data attached to the message
        /// </summary>
        [JsonProperty("@extra")]
        public override string Extra { get; set; }


    }
}
// REUSE-IgnoreEnd