using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Describes an option for the number of winners of a Telegram Star giveaway
        /// </summary>
        public partial class StarGiveawayWinnerOption : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "starGiveawayWinnerOption";

            /// <summary>
            /// Extra data attached to the object
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// The number of users that will be chosen as winners
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("winner_count")]
            public int WinnerCount { get; set; }

            /// <summary>
            /// The number of Telegram Stars that will be won by the winners of the giveaway
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("won_star_count")]
            public long WonStarCount { get; set; }

            /// <summary>
            /// True, if the option must be chosen by default
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("is_default")]
            public bool IsDefault { get; set; }
        }
    }
}
// REUSE-IgnoreEnd