using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class StatisticalGraph : Object
        {
            /// <summary>
            /// Describes a statistical graph
            /// </summary>
            public class StatisticalGraphData : StatisticalGraph
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "statisticalGraphData";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Graph data in JSON format
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("json_data")]
                public string JsonData { get; set; }

                /// <summary>
                /// If non-empty, a token which can be used to receive a zoomed in graph
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("zoom_token")]
                public string ZoomToken { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd