using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Returns information about the availability of a temporary password, which can be used for payments 
        /// </summary>
        public class TemporaryPasswordState : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "temporaryPasswordState";

            /// <summary>
            /// Extra data attached to the message
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// True, if a temporary password is available 
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("has_password")]
            public bool HasPassword { get; set; }

            /// <summary>
            /// Time left before the temporary password expires, in seconds
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("valid_for")]
            public int ValidFor { get; set; }
        }
    }
}