using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
namespace TdLib.TdApi.Objects;
public partial class TextEntityType : Object
{
    /// <summary>
    /// A hashtag text, beginning with "#" and optionally containing a chat username at the end
    /// </summary>
    public class TextEntityTypeHashtag : TextEntityType
    {
        /// <summary>
        /// Data type for serialization
        /// </summary>
        [JsonProperty("@type")]
        public override string DataType { get; set; } = "textEntityTypeHashtag";

        /// <summary>
        /// Extra data attached to the message
        /// </summary>
        [JsonProperty("@extra")]
        public override string Extra { get; set; }


    }
}
// REUSE-IgnoreEnd