using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
namespace TdLib.TdApi.Objects;
public partial class ThumbnailFormat : Object
{
    /// <summary>
    /// The thumbnail is in static GIF format. It will be used only for some bot inline query results
    /// </summary>
    public class ThumbnailFormatGif : ThumbnailFormat
    {
        /// <summary>
        /// Data type for serialization
        /// </summary>
        [JsonProperty("@type")]
        public override string DataType { get; set; } = "thumbnailFormatGif";

        /// <summary>
        /// Extra data attached to the message
        /// </summary>
        [JsonProperty("@extra")]
        public override string Extra { get; set; }


    }
}
// REUSE-IgnoreEnd