using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
namespace TdLib.TdApi.Objects;
public partial class TopChatCategory : Object
{
    /// <summary>
    /// A category containing frequently used chats used to forward messages
    /// </summary>
    public class TopChatCategoryForwardChats : TopChatCategory
    {
        /// <summary>
        /// Data type for serialization
        /// </summary>
        [JsonProperty("@type")]
        public override string DataType { get; set; } = "topChatCategoryForwardChats";

        /// <summary>
        /// Extra data attached to the message
        /// </summary>
        [JsonProperty("@extra")]
        public override string Extra { get; set; }


    }
}
// REUSE-IgnoreEnd