using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class Update : Object
        {
            /// <summary>
            /// Basic information about a topic in a channel direct messages chat administered by the current user has changed. This update is guaranteed to come before the topic identifier is returned to the application
            /// </summary>
            public class UpdateDirectMessagesChatTopic : Update
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateDirectMessagesChatTopic";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// New data about the topic
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("topic")]
                public DirectMessagesChatTopic Topic { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd