using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class Update : Object
        {
            /// <summary>
            /// A new incoming guest query; for bots only
            /// </summary>
            public class UpdateNewGuestQuery : Update
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateNewGuestQuery";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Unique query identifier
                /// </summary>
                [JsonConverter(typeof(Converter.Int64))]
                [JsonProperty("id")]
                public long Id { get; set; }

                /// <summary>
                /// The message with the query
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("message")]
                public Message Message { get; set; }

                /// <summary>
                /// The list of reference messages
                /// </summary>
                [JsonProperty("reference_messages", ItemConverterType = typeof(Converter))]
                public Message[] ReferenceMessages { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd