using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class Update : Object
        {
            /// <summary>
            /// The message auto-delete or self-destruct timer setting for a chat was changed
            /// </summary>
            public class UpdateChatMessageAutoDeleteTime : Update
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateChatMessageAutoDeleteTime";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Chat identifier
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("chat_id")]
                public long ChatId { get; set; }

                /// <summary>
                /// New value of message_auto_delete_time
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("message_auto_delete_time")]
                public int MessageAutoDeleteTime { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd