using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class Update : Object
        {
            /// <summary>
            /// Messages in a business account were deleted; for bots only
            /// </summary>
            public class UpdateBusinessMessagesDeleted : Update
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateBusinessMessagesDeleted";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Unique identifier of the business connection
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("connection_id")]
                public string ConnectionId { get; set; }

                /// <summary>
                /// Identifier of a chat in the business account in which messages were deleted
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("chat_id")]
                public long ChatId { get; set; }

                /// <summary>
                /// Unique message identifiers of the deleted messages
                /// </summary>
                [JsonProperty("message_ids", ItemConverterType = typeof(Converter))]
                public long[] MessageIds { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd