using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class Update : Object
        {
            /// <summary>
            /// The list of quick reply shortcuts has changed
            /// </summary>
            public class UpdateQuickReplyShortcuts : Update
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateQuickReplyShortcuts";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// The new list of identifiers of quick reply shortcuts
                /// </summary>
                [JsonProperty("shortcut_ids", ItemConverterType = typeof(Converter))]
                public int[] ShortcutIds { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd