using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class Update : Object
        {
            /// <summary>
            /// A message draft generation was stopped by the user
            /// </summary>
            public class UpdateStopMessageDraft : Update
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateStopMessageDraft";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Chat identifier
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("chat_id")]
                public long ChatId { get; set; }

                /// <summary>
                /// The forum topic identifier of the message draft
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("forum_topic_id")]
                public int ForumTopicId { get; set; }

                /// <summary>
                /// Identifier of the message draft within the message thread
                /// </summary>
                [JsonConverter(typeof(Converter.Int64))]
                [JsonProperty("draft_id")]
                public long DraftId { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd