using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// The list of trending sticker sets was updated or some of them were viewed 
        /// </summary>
        public partial class Update : Object
        {
            /// <summary>
            /// The list of trending sticker sets was updated or some of them were viewed 
            /// </summary>
            public class UpdateTrendingStickerSets : Update
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateTrendingStickerSets";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// The new list of trending sticker sets
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("sticker_sets")]
                public StickerSets StickerSets { get; set; }
            }
        }
    }
}