using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class Update : Object
        {
            /// <summary>
            /// Paid media were purchased by a user; for bots only
            /// </summary>
            public class UpdatePaidMediaPurchased : Update
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updatePaidMediaPurchased";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// User identifier
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("user_id")]
                public long UserId { get; set; }

                /// <summary>
                /// Bot-specified payload for the paid media
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("payload")]
                public string Payload { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd