using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// The user went online or offline 
        /// </summary>
        public partial class Update : Object
        {
            /// <summary>
            /// The user went online or offline 
            /// </summary>
            public class UpdateUserStatus : Update
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateUserStatus";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// User identifier 
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("user_id")]
                public int UserId { get; set; }

                /// <summary>
                /// New status of the user
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("status")]
                public UserStatus Status { get; set; }
            }
        }
    }
}