using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class Update : Object
        {
            /// <summary>
            /// A new pending text message was received in a chat with a bot. The message must be shown in the chat for at most getOption("pending_text_message_period") seconds,
            /// replace any other pending message with the same draft_id, and be deleted whenever any incoming message from the bot in the message thread is received
            /// </summary>
            public class UpdatePendingTextMessage : Update
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updatePendingTextMessage";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// Chat identifier
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("chat_id")]
                public long ChatId { get; set; }

                /// <summary>
                /// The forum topic identifier in which the message will be sent; 0 if none
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("forum_topic_id")]
                public int ForumTopicId { get; set; }

                /// <summary>
                /// Unique identifier of the message draft within the message thread
                /// </summary>
                [JsonConverter(typeof(Converter.Int64))]
                [JsonProperty("draft_id")]
                public long DraftId { get; set; }

                /// <summary>
                /// Text of the pending message
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("text")]
                public FormattedText Text { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd