using System;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        public partial class Update : Object
        {
            /// <summary>
            /// The freeze state of the current user's account has changed
            /// </summary>
            public class UpdateFreezeState : Update
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "updateFreezeState";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                /// <summary>
                /// True, if the account is frozen
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("is_frozen")]
                public bool IsFrozen { get; set; }

                /// <summary>
                /// Point in time (Unix timestamp) when the account was frozen; 0 if the account isn't frozen
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("freezing_date")]
                public int FreezingDate { get; set; }

                /// <summary>
                /// Point in time (Unix timestamp) when the account will be deleted and can't be unfrozen; 0 if the account isn't frozen
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("deletion_date")]
                public int DeletionDate { get; set; }

                /// <summary>
                /// The link to open to send an appeal to unfreeze the account
                /// </summary>
                [JsonConverter(typeof(Converter))]
                [JsonProperty("appeal_link")]
                public string AppealLink { get; set; }
            }
        }
    }
}
// REUSE-IgnoreEnd