using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// A rule to restrict all contacts of a user from doing something
        /// </summary>
        public partial class UserPrivacySettingRule : Object
        {
            /// <summary>
            /// A rule to restrict all contacts of a user from doing something
            /// </summary>
            public class UserPrivacySettingRuleRestrictContacts : UserPrivacySettingRule
            {
                /// <summary>
                /// Data type for serialization
                /// </summary>
                [JsonProperty("@type")]
                public override string DataType { get; set; } = "userPrivacySettingRuleRestrictContacts";

                /// <summary>
                /// Extra data attached to the message
                /// </summary>
                [JsonProperty("@extra")]
                public override string Extra { get; set; }
            }
        }
    }
}