using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TdApi
    {
        public class WebPageInstantView : Object
        {
            [JsonProperty("@type")] public override string DataType { get; set; } = "webPageInstantView";

            [JsonProperty("@extra")] public override string Extra { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("page_blocks")]
            public PageBlock[] PageBlocks { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("is_full")]
            public bool IsFull { get; set; }
        }
    }
}