using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Accepts an incoming call
/// </summary>
public class AcceptCall : Function<Ok>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "acceptCall";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Call identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("call_id")]
            public int CallId { get; set; }

            /// <summary>
            /// The call protocols supported by the application
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("protocol")]
            public CallProtocol Protocol { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Accepts an incoming call
    /// </summary>
    public Task<Ok> AcceptCallAsync(int callId = default, CallProtocol protocol = default)
    {
    //test
        return ExecuteAsync(new AcceptCall
        {
            CallId = callId, Protocol = protocol
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Accepts an incoming call
    /// </summary>
    Task<Ok> AcceptCallAsync(int callId = default, CallProtocol protocol = default);
}


// REUSE-IgnoreEnd