using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Adds a custom text composition style to the list of used by the user styles. May return an error with a message "TONES_SAVED_TOO_MANY"
        /// if the maximum number of added custom styles getOption("added_text_composition_style_count_max") has been reached
        /// </summary>
        public class AddTextCompositionStyle : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "addTextCompositionStyle";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Name of the style
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("name")]
            public string Name { get; set; }
        }

        /// <summary>
        /// Adds a custom text composition style to the list of used by the user styles. May return an error with a message "TONES_SAVED_TOO_MANY"
        /// if the maximum number of added custom styles getOption("added_text_composition_style_count_max") has been reached
        /// </summary>
        public static Task<Ok> AddTextCompositionStyleAsync(
            this IClient client, string name = default)
        {
            return client.ExecuteAsync(new AddTextCompositionStyle
            {
                Name = name
            });
        }
    }
}
// REUSE-IgnoreEnd