using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Checks a passkey to log in to the corresponding account. Call getAuthenticationPasskeyParameters to get parameters for the passkey. Works only when the current authorization state is
/// authorizationStateWaitPhoneNumber or authorizationStateWaitOtherDeviceConfirmation, or if there is no pending authentication query and the current authorization state is
/// authorizationStateWaitPremiumPurchase, authorizationStateWaitEmailAddress, authorizationStateWaitEmailCode, authorizationStateWaitCode, authorizationStateWaitRegistration, or authorizationStateWaitPassword
/// </summary>
public class CheckAuthenticationPasskey : Function<Ok>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "checkAuthenticationPasskey";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Base64url-encoded identifier of the credential
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("credential_id")]
            public string CredentialId { get; set; }

            /// <summary>
            /// JSON-encoded client data
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("client_data")]
            public string ClientData { get; set; }

            /// <summary>
            /// Authenticator data of the application that created the credential
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("authenticator_data")]
            public byte[] AuthenticatorData { get; set; }

            /// <summary>
            /// Cryptographic signature of the credential
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("signature")]
            public byte[] Signature { get; set; }

            /// <summary>
            /// User handle of the passkey
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("user_handle")]
            public byte[] UserHandle { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public static partial class ClientExtensions
{
    /// <summary>
    /// Checks a passkey to log in to the corresponding account. Call getAuthenticationPasskeyParameters to get parameters for the passkey. Works only when the current authorization state is
    /// authorizationStateWaitPhoneNumber or authorizationStateWaitOtherDeviceConfirmation, or if there is no pending authentication query and the current authorization state is
    /// authorizationStateWaitPremiumPurchase, authorizationStateWaitEmailAddress, authorizationStateWaitEmailCode, authorizationStateWaitCode, authorizationStateWaitRegistration, or authorizationStateWaitPassword
    /// </summary>
    public static Task<Ok> CheckAuthenticationPasskeyAsync(
        this Client client, string credentialId = default, string clientData = default, byte[] authenticatorData = default, byte[] signature = default, byte[] userHandle = default)
    {
        return client.ExecuteAsync(new CheckAuthenticationPasskey
        {
            CredentialId = credentialId, ClientData = clientData, AuthenticatorData = authenticatorData, Signature = signature, UserHandle = userHandle
        });
    }
}
public partial class Client
{
    /// <summary>
    /// Checks a passkey to log in to the corresponding account. Call getAuthenticationPasskeyParameters to get parameters for the passkey. Works only when the current authorization state is
    /// authorizationStateWaitPhoneNumber or authorizationStateWaitOtherDeviceConfirmation, or if there is no pending authentication query and the current authorization state is
    /// authorizationStateWaitPremiumPurchase, authorizationStateWaitEmailAddress, authorizationStateWaitEmailCode, authorizationStateWaitCode, authorizationStateWaitRegistration, or authorizationStateWaitPassword
    /// </summary>
    public Task<Ok> CheckAuthenticationPasskeyAsync(string credentialId = default, string clientData = default, byte[] authenticatorData = default, byte[] signature = default, byte[] userHandle = default)
    {
    //test
        return ExecuteAsync(new CheckAuthenticationPasskey
        {
            CredentialId = credentialId, ClientData = clientData, AuthenticatorData = authenticatorData, Signature = signature, UserHandle = userHandle
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Checks a passkey to log in to the corresponding account. Call getAuthenticationPasskeyParameters to get parameters for the passkey. Works only when the current authorization state is
    /// authorizationStateWaitPhoneNumber or authorizationStateWaitOtherDeviceConfirmation, or if there is no pending authentication query and the current authorization state is
    /// authorizationStateWaitPremiumPurchase, authorizationStateWaitEmailAddress, authorizationStateWaitEmailCode, authorizationStateWaitCode, authorizationStateWaitRegistration, or authorizationStateWaitPassword
    /// </summary>
    Task<Ok> CheckAuthenticationPasskeyAsync(string credentialId = default, string clientData = default, byte[] authenticatorData = default, byte[] signature = default, byte[] userHandle = default);
}


// REUSE-IgnoreEnd