using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Return information about a Telegram Premium gift code
        /// </summary>
        public class CheckPremiumGiftCode : Function<PremiumGiftCodeInfo>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "checkPremiumGiftCode";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// The code to check
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("code")]
            public string Code { get; set; }
        }

        /// <summary>
        /// Return information about a Telegram Premium gift code
        /// </summary>
        public static Task<PremiumGiftCodeInfo> CheckPremiumGiftCodeAsync(
            this Client client, string code = default)
        {
            return client.ExecuteAsync(new CheckPremiumGiftCode
            {
                Code = code
            });
        }
    }
}
// REUSE-IgnoreEnd