using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Clears all imported contacts, contact list remains unchanged
/// </summary>
public class ClearImportedContacts : Function<Ok>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "clearImportedContacts";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }


}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Clears all imported contacts, contact list remains unchanged
    /// </summary>
    public Task<Ok> ClearImportedContactsAsync()
    {
    //test
        return ExecuteAsync(new ClearImportedContacts
        {
            
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Clears all imported contacts, contact list remains unchanged
    /// </summary>
    Task<Ok> ClearImportedContactsAsync();
}


// REUSE-IgnoreEnd