using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Clears the list of recently searched for hashtags or cashtags
/// </summary>
public class ClearSearchedForTags : Function<Ok>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "clearSearchedForTags";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Pass true to clear the list of recently searched for cashtags; otherwise, the list of recently searched for hashtags will be cleared
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("clear_cashtags")]
            public bool ClearCashtags { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Clears the list of recently searched for hashtags or cashtags
    /// </summary>
    public Task<Ok> ClearSearchedForTagsAsync(bool clearCashtags = default)
    {
    //test
        return ExecuteAsync(new ClearSearchedForTags
        {
            ClearCashtags = clearCashtags
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Clears the list of recently searched for hashtags or cashtags
    /// </summary>
    Task<Ok> ClearSearchedForTagsAsync(bool clearCashtags = default);
}


// REUSE-IgnoreEnd