using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Informs TDLib that a gift auction was closed by the user
        /// </summary>
        public class CloseGiftAuction : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "closeGiftAuction";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the gift, which auction was closed
            /// </summary>
            [JsonConverter(typeof(Converter.Int64))]
            [JsonProperty("gift_id")]
            public long GiftId { get; set; }
        }

        /// <summary>
        /// Informs TDLib that a gift auction was closed by the user
        /// </summary>
        public static Task<Ok> CloseGiftAuctionAsync(
            this Client client, long giftId = default)
        {
            return client.ExecuteAsync(new CloseGiftAuction
            {
                GiftId = giftId
            });
        }
    }
}
// REUSE-IgnoreEnd