using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Creates a link for the given invoice; for bots only
/// </summary>
public class CreateInvoiceLink : Function<HttpUrl>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "createInvoiceLink";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Unique identifier of business connection on behalf of which to send the request
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("business_connection_id")]
            public string BusinessConnectionId { get; set; }

            /// <summary>
            /// Information about the invoice of the type inputMessageInvoice
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("invoice")]
            public InputMessageContent Invoice { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public static partial class ClientExtensions
{
    /// <summary>
    /// Creates a link for the given invoice; for bots only
    /// </summary>
    public static Task<HttpUrl> CreateInvoiceLinkAsync(
        this Client client, string businessConnectionId = default, InputMessageContent invoice = default)
    {
        return client.ExecuteAsync(new CreateInvoiceLink
        {
            BusinessConnectionId = businessConnectionId, Invoice = invoice
        });
    }
}
public partial class Client
{
    /// <summary>
    /// Creates a link for the given invoice; for bots only
    /// </summary>
    public Task<HttpUrl> CreateInvoiceLinkAsync(string businessConnectionId = default, InputMessageContent invoice = default)
    {
    //test
        return ExecuteAsync(new CreateInvoiceLink
        {
            BusinessConnectionId = businessConnectionId, Invoice = invoice
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Creates a link for the given invoice; for bots only
    /// </summary>
    Task<HttpUrl> CreateInvoiceLinkAsync(string businessConnectionId = default, InputMessageContent invoice = default);
}


// REUSE-IgnoreEnd