using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Deletes all messages sent by the specified message sender in a group call; for live story calls only. Requires groupCall.can_delete_messages right
/// </summary>
public class DeleteGroupCallMessagesBySender : Function<Ok>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "deleteGroupCallMessagesBySender";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Group call identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("group_call_id")]
            public int GroupCallId { get; set; }

            /// <summary>
            /// Identifier of the sender of messages to delete
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("sender_id")]
            public MessageSender SenderId { get; set; }

            /// <summary>
            /// Pass true to report the messages as spam
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("report_spam")]
            public bool ReportSpam { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public static partial class ClientExtensions
{
    /// <summary>
    /// Deletes all messages sent by the specified message sender in a group call; for live story calls only. Requires groupCall.can_delete_messages right
    /// </summary>
    public static Task<Ok> DeleteGroupCallMessagesBySenderAsync(
        this Client client, int groupCallId = default, MessageSender senderId = default, bool reportSpam = default)
    {
        return client.ExecuteAsync(new DeleteGroupCallMessagesBySender
        {
            GroupCallId = groupCallId, SenderId = senderId, ReportSpam = reportSpam
        });
    }
}
public partial class Client
{
    /// <summary>
    /// Deletes all messages sent by the specified message sender in a group call; for live story calls only. Requires groupCall.can_delete_messages right
    /// </summary>
    public Task<Ok> DeleteGroupCallMessagesBySenderAsync(int groupCallId = default, MessageSender senderId = default, bool reportSpam = default)
    {
    //test
        return ExecuteAsync(new DeleteGroupCallMessagesBySender
        {
            GroupCallId = groupCallId, SenderId = senderId, ReportSpam = reportSpam
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Deletes all messages sent by the specified message sender in a group call; for live story calls only. Requires groupCall.can_delete_messages right
    /// </summary>
    Task<Ok> DeleteGroupCallMessagesBySenderAsync(int groupCallId = default, MessageSender senderId = default, bool reportSpam = default);
}


// REUSE-IgnoreEnd