using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Deletes existing chat filter
        /// </summary>
        public class DeleteChatFilter : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "deleteChatFilter";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Chat filter identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_filter_id")]
            public int ChatFilterId { get; set; }
        }

        /// <summary>
        /// Deletes existing chat filter
        /// </summary>
        public static Task<Ok> DeleteChatFilterAsync(
            this Client client, int chatFilterId = default)
        {
            return client.ExecuteAsync(new DeleteChatFilter
            {
                ChatFilterId = chatFilterId
            });
        }
    }
}