using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Deletes all revoked chat invite links created by a given chat administrator. Requires administrator privileges and can_invite_users right in the chat for own links and owner privileges for other links
        /// </summary>
        public class DeleteAllRevokedChatInviteLinks : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "deleteAllRevokedChatInviteLinks";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Chat identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// User identifier of a chat administrator, which links will be deleted. Must be an identifier of the current user for non-owner
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("creator_user_id")]
            public long CreatorUserId { get; set; }
        }

        /// <summary>
        /// Deletes all revoked chat invite links created by a given chat administrator. Requires administrator privileges and can_invite_users right in the chat for own links and owner privileges for other links
        /// </summary>
        public static Task<Ok> DeleteAllRevokedChatInviteLinksAsync(
            this Client client, long chatId = default, long creatorUserId = default)
        {
            return client.ExecuteAsync(new DeleteAllRevokedChatInviteLinks
            {
                ChatId = chatId, CreatorUserId = creatorUserId
            });
        }
    }
}
// REUSE-IgnoreEnd