using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Returns autosave settings for the current user
/// </summary>
public class GetAutosaveSettings : Function<AutosaveSettings>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getAutosaveSettings";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }


}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public static partial class ClientExtensions
{
    /// <summary>
    /// Returns autosave settings for the current user
    /// </summary>
    public static Task<AutosaveSettings> GetAutosaveSettingsAsync(
        this Client client)
    {
        return client.ExecuteAsync(new GetAutosaveSettings
        {
            
        });
    }
}
public partial class Client
{
    /// <summary>
    /// Returns autosave settings for the current user
    /// </summary>
    public Task<AutosaveSettings> GetAutosaveSettingsAsync()
    {
    //test
        return ExecuteAsync(new GetAutosaveSettings
        {
            
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Returns autosave settings for the current user
    /// </summary>
    Task<AutosaveSettings> GetAutosaveSettingsAsync();
}


// REUSE-IgnoreEnd