using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Returns the period of inactivity after which the account of the current user will automatically be deleted
/// </summary>
public class GetAccountTtl : Function<AccountTtl>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getAccountTtl";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }


}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Returns the period of inactivity after which the account of the current user will automatically be deleted
    /// </summary>
    public Task<AccountTtl> GetAccountTtlAsync()
    {
    //test
        return ExecuteAsync(new GetAccountTtl
        {
            
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Returns the period of inactivity after which the account of the current user will automatically be deleted
    /// </summary>
    Task<AccountTtl> GetAccountTtlAsync();
}


// REUSE-IgnoreEnd