using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Constructs a persistent HTTP URL for a background
/// </summary>
public class GetBackgroundUrl : Function<HttpUrl>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getBackgroundUrl";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Background name
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("name")]
            public string Name { get; set; }

            /// <summary>
            /// Background type; backgroundTypeChatTheme isn't supported
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("type")]
            public BackgroundType Type { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public static partial class ClientExtensions
{
    /// <summary>
    /// Constructs a persistent HTTP URL for a background
    /// </summary>
    public static Task<HttpUrl> GetBackgroundUrlAsync(
        this Client client, string name = default, BackgroundType type = default)
    {
        return client.ExecuteAsync(new GetBackgroundUrl
        {
            Name = name, Type = type
        });
    }
}
public partial class Client
{
    /// <summary>
    /// Constructs a persistent HTTP URL for a background
    /// </summary>
    public Task<HttpUrl> GetBackgroundUrlAsync(string name = default, BackgroundType type = default)
    {
    //test
        return ExecuteAsync(new GetBackgroundUrl
        {
            Name = name, Type = type
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Constructs a persistent HTTP URL for a background
    /// </summary>
    Task<HttpUrl> GetBackgroundUrlAsync(string name = default, BackgroundType type = default);
}


// REUSE-IgnoreEnd