using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Returns information about features, available to Business users
/// </summary>
public class GetBusinessFeatures : Function<BusinessFeatures>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getBusinessFeatures";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Source of the request; pass null if the method is called from settings or some non-standard source
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("source")]
            public BusinessFeature Source { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public static partial class ClientExtensions
{
    /// <summary>
    /// Returns information about features, available to Business users
    /// </summary>
    public static Task<BusinessFeatures> GetBusinessFeaturesAsync(
        this Client client, BusinessFeature source = default)
    {
        return client.ExecuteAsync(new GetBusinessFeatures
        {
            Source = source
        });
    }
}
public partial class Client
{
    /// <summary>
    /// Returns information about features, available to Business users
    /// </summary>
    public Task<BusinessFeatures> GetBusinessFeaturesAsync(BusinessFeature source = default)
    {
    //test
        return ExecuteAsync(new GetBusinessFeatures
        {
            Source = source
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Returns information about features, available to Business users
    /// </summary>
    Task<BusinessFeatures> GetBusinessFeaturesAsync(BusinessFeature source = default);
}


// REUSE-IgnoreEnd