using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TdApi
    {
        public class GetBasicGroupFullInfo : Function<BasicGroupFullInfo>
        {
            [JsonProperty("@type")] public override string DataType { get; set; } = "getBasicGroupFullInfo";

            [JsonProperty("@extra")] public override string Extra { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("basic_group_id")]
            public int BasicGroupId { get; set; }
        }
    }
}