using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Returns an HTTPS link to boost the specified supergroup or channel chat
/// </summary>
public class GetChatBoostLink : Function<ChatBoostLink>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getChatBoostLink";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the chat
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Returns an HTTPS link to boost the specified supergroup or channel chat
    /// </summary>
    public Task<ChatBoostLink> GetChatBoostLinkAsync(long chatId = default)
    {
    //test
        return ExecuteAsync(new GetChatBoostLink
        {
            ChatId = chatId
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Returns an HTTPS link to boost the specified supergroup or channel chat
    /// </summary>
    Task<ChatBoostLink> GetChatBoostLinkAsync(long chatId = default);
}


// REUSE-IgnoreEnd