using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Returns the list of active stories posted by the given chat
/// </summary>
public class GetChatActiveStories : Function<ChatActiveStories>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getChatActiveStories";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Chat identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Returns the list of active stories posted by the given chat
    /// </summary>
    public Task<ChatActiveStories> GetChatActiveStoriesAsync(long chatId = default)
    {
    //test
        return ExecuteAsync(new GetChatActiveStories
        {
            ChatId = chatId
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Returns the list of active stories posted by the given chat
    /// </summary>
    Task<ChatActiveStories> GetChatActiveStoriesAsync(long chatId = default);
}


// REUSE-IgnoreEnd