using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Returns the list of revenue transactions for a chat. Currently, this method can be used only
/// for channels if supergroupFullInfo.can_get_revenue_statistics == true or bots if userFullInfo.bot_info.can_get_revenue_statistics == true
/// </summary>
public class GetChatRevenueTransactions : Function<ChatRevenueTransactions>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getChatRevenueTransactions";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Chat identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// Offset of the first transaction to return as received from the previous request; use empty string to get the first chunk of results
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("offset")]
            public string Offset { get; set; }

            /// <summary>
            /// The maximum number of transactions to be returned; up to 100
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("limit")]
            public int Limit { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Returns the list of revenue transactions for a chat. Currently, this method can be used only
    /// for channels if supergroupFullInfo.can_get_revenue_statistics == true or bots if userFullInfo.bot_info.can_get_revenue_statistics == true
    /// </summary>
    public Task<ChatRevenueTransactions> GetChatRevenueTransactionsAsync(long chatId = default, string offset = default, int limit = default)
    {
    //test
        return ExecuteAsync(new GetChatRevenueTransactions
        {
            ChatId = chatId, Offset = offset, Limit = limit
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Returns the list of revenue transactions for a chat. Currently, this method can be used only
    /// for channels if supergroupFullInfo.can_get_revenue_statistics == true or bots if userFullInfo.bot_info.can_get_revenue_statistics == true
    /// </summary>
    Task<ChatRevenueTransactions> GetChatRevenueTransactionsAsync(long chatId = default, string offset = default, int limit = default);
}


// REUSE-IgnoreEnd