using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Returns information about an emoji reaction. Returns a 404 error if the reaction is not found
/// </summary>
public class GetEmojiReaction : Function<EmojiReaction>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getEmojiReaction";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Text representation of the reaction
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("emoji")]
            public string Emoji { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Returns information about an emoji reaction. Returns a 404 error if the reaction is not found
    /// </summary>
    public Task<EmojiReaction> GetEmojiReactionAsync(string emoji = default)
    {
    //test
        return ExecuteAsync(new GetEmojiReaction
        {
            Emoji = emoji
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Returns information about an emoji reaction. Returns a 404 error if the reaction is not found
    /// </summary>
    Task<EmojiReaction> GetEmojiReactionAsync(string emoji = default);
}


// REUSE-IgnoreEnd