using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Returns upgraded gifts of the current user who can be used to craft another gifts
        /// </summary>
        public class GetGiftsForCrafting : Function<GiftsForCrafting>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "getGiftsForCrafting";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the regular gift that will be used for crafting
            /// </summary>
            [JsonConverter(typeof(Converter.Int64))]
            [JsonProperty("regular_gift_id")]
            public long RegularGiftId { get; set; }

            /// <summary>
            /// Offset of the first entry to return as received from the previous request; use empty string to get the first chunk of results
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("offset")]
            public string Offset { get; set; }

            /// <summary>
            /// The maximum number of gifts to be returned; must be positive and can't be greater than 100. For optimal performance, the number of returned objects is chosen by TDLib and can be smaller than the specified limit
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("limit")]
            public int Limit { get; set; }
        }

        /// <summary>
        /// Returns upgraded gifts of the current user who can be used to craft another gifts
        /// </summary>
        public static Task<GiftsForCrafting> GetGiftsForCraftingAsync(
            this Client client, long regularGiftId = default, string offset = default, int limit = default)
        {
            return client.ExecuteAsync(new GetGiftsForCrafting
            {
                RegularGiftId = regularGiftId, Offset = offset, Limit = limit
            });
        }
    }
}
// REUSE-IgnoreEnd