using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Returns collections of gifts owned by the given user or chat
/// </summary>
public class GetGiftCollections : Function<GiftCollections>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getGiftCollections";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the user or the channel chat that received the gifts
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("owner_id")]
            public MessageSender OwnerId { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Returns collections of gifts owned by the given user or chat
    /// </summary>
    public Task<GiftCollections> GetGiftCollectionsAsync(MessageSender ownerId = default)
    {
    //test
        return ExecuteAsync(new GetGiftCollections
        {
            OwnerId = ownerId
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Returns collections of gifts owned by the given user or chat
    /// </summary>
    Task<GiftCollections> GetGiftCollectionsAsync(MessageSender ownerId = default);
}


// REUSE-IgnoreEnd