using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Returns the total number of imported contacts
/// </summary>
public class GetImportedContactCount : Function<Count>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getImportedContactCount";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }


}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Returns the total number of imported contacts
    /// </summary>
    public Task<Count> GetImportedContactCountAsync()
    {
    //test
        return ExecuteAsync(new GetImportedContactCount
        {
            
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Returns the total number of imported contacts
    /// </summary>
    Task<Count> GetImportedContactCountAsync();
}


// REUSE-IgnoreEnd