using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Returns the list of bots owned by the current user
/// </summary>
public class GetOwnedBots : Function<Users>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getOwnedBots";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }


}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public static partial class ClientExtensions
{
    /// <summary>
    /// Returns the list of bots owned by the current user
    /// </summary>
    public static Task<Users> GetOwnedBotsAsync(
        this Client client)
    {
        return client.ExecuteAsync(new GetOwnedBots
        {
            
        });
    }
}
public partial class Client
{
    /// <summary>
    /// Returns the list of bots owned by the current user
    /// </summary>
    public Task<Users> GetOwnedBotsAsync()
    {
    //test
        return ExecuteAsync(new GetOwnedBots
        {
            
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Returns the list of bots owned by the current user
    /// </summary>
    Task<Users> GetOwnedBotsAsync();
}


// REUSE-IgnoreEnd