using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Returns available options for gifting Telegram Premium to a user
        /// </summary>
        public class GetPremiumGiftPaymentOptions : Function<PremiumGiftPaymentOptions>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "getPremiumGiftPaymentOptions";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }


        }

        /// <summary>
        /// Returns available options for gifting Telegram Premium to a user
        /// </summary>
        public static Task<PremiumGiftPaymentOptions> GetPremiumGiftPaymentOptionsAsync(
            this Client client)
        {
            return client.ExecuteAsync(new GetPremiumGiftPaymentOptions
            {
                
            });
        }
    }
}
// REUSE-IgnoreEnd