using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TdApi
    {
        public class GetProxyLink : Function<Text>
        {
            [JsonProperty("@type")] public override string DataType { get; set; } = "getProxyLink";

            [JsonProperty("@extra")] public override string Extra { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("proxy_id")]
            public int ProxyId { get; set; }
        }
    }
}