using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Returns a public HTTPS link to a message. Available only for messages in supergroups and channels with a username
        /// </summary>
        public class GetPublicMessageLink : Function<PublicMessageLink>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "getPublicMessageLink";

            /// <summary>
            /// Extra data attached to the message
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the chat to which the message belongs
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// Identifier of the message
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("message_id")]
            public long MessageId { get; set; }

            /// <summary>
            /// Pass true if a link for a whole media album should be returned
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("for_album")]
            public bool ForAlbum { get; set; }
        }


        /// <summary>
        /// Returns a public HTTPS link to a message. Available only for messages in supergroups and channels with a username
        /// </summary>
        public static Task<PublicMessageLink> GetPublicMessageLinkAsync(this Client client,
            long chatId = default(long),
            long messageId = default(long),
            bool forAlbum = default(bool))
        {
            return client.ExecuteAsync(new GetPublicMessageLink
            {
                ChatId = chatId,
                MessageId = messageId,
                ForAlbum = forAlbum,
            });
        }
    }
}