using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Returns information about features, available to Premium users
/// </summary>
public class GetPremiumFeatures : Function<PremiumFeatures>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getPremiumFeatures";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Source of the request; pass null if the method is called from some non-standard source
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("source")]
            public PremiumSource Source { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public static partial class ClientExtensions
{
    /// <summary>
    /// Returns information about features, available to Premium users
    /// </summary>
    public static Task<PremiumFeatures> GetPremiumFeaturesAsync(
        this Client client, PremiumSource source = default)
    {
        return client.ExecuteAsync(new GetPremiumFeatures
        {
            Source = source
        });
    }
}
public partial class Client
{
    /// <summary>
    /// Returns information about features, available to Premium users
    /// </summary>
    public Task<PremiumFeatures> GetPremiumFeaturesAsync(PremiumSource source = default)
    {
    //test
        return ExecuteAsync(new GetPremiumFeatures
        {
            Source = source
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Returns information about features, available to Premium users
    /// </summary>
    Task<PremiumFeatures> GetPremiumFeaturesAsync(PremiumSource source = default);
}


// REUSE-IgnoreEnd