using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Returns information about a received gift
        /// </summary>
        public class GetReceivedGift : Function<ReceivedGift>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "getReceivedGift";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the gift
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("received_gift_id")]
            public string ReceivedGiftId { get; set; }
        }

        /// <summary>
        /// Returns information about a received gift
        /// </summary>
        public static Task<ReceivedGift> GetReceivedGiftAsync(
            this Client client, string receivedGiftId = default)
        {
            return client.ExecuteAsync(new GetReceivedGift
            {
                ReceivedGiftId = receivedGiftId
            });
        }
    }
}
// REUSE-IgnoreEnd