using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Returns a story
        /// </summary>
        public class GetStory : Function<Story>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "getStory";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the chat that posted the story
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("story_sender_chat_id")]
            public long StorySenderChatId { get; set; }

            /// <summary>
            /// Story identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("story_id")]
            public int StoryId { get; set; }

            /// <summary>
            /// Pass true to get only locally available information without sending network requests
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("only_local")]
            public bool OnlyLocal { get; set; }
        }

        /// <summary>
        /// Returns a story
        /// </summary>
        public static Task<Story> GetStoryAsync(
            this Client client, long storySenderChatId = default, int storyId = default, bool onlyLocal = default)
        {
            return client.ExecuteAsync(new GetStory
            {
                StorySenderChatId = storySenderChatId, StoryId = storyId, OnlyLocal = onlyLocal
            });
        }
    }
}
// REUSE-IgnoreEnd