using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Returns tags used in Saved Messages or a Saved Messages topic
/// </summary>
public class GetSavedMessagesTags : Function<SavedMessagesTags>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getSavedMessagesTags";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Identifier of Saved Messages topic which tags will be returned; pass 0 to get all Saved Messages tags
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("saved_messages_topic_id")]
            public long SavedMessagesTopicId { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public static partial class ClientExtensions
{
    /// <summary>
    /// Returns tags used in Saved Messages or a Saved Messages topic
    /// </summary>
    public static Task<SavedMessagesTags> GetSavedMessagesTagsAsync(
        this Client client, long savedMessagesTopicId = default)
    {
        return client.ExecuteAsync(new GetSavedMessagesTags
        {
            SavedMessagesTopicId = savedMessagesTopicId
        });
    }
}
public partial class Client
{
    /// <summary>
    /// Returns tags used in Saved Messages or a Saved Messages topic
    /// </summary>
    public Task<SavedMessagesTags> GetSavedMessagesTagsAsync(long savedMessagesTopicId = default)
    {
    //test
        return ExecuteAsync(new GetSavedMessagesTags
        {
            SavedMessagesTopicId = savedMessagesTopicId
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Returns tags used in Saved Messages or a Saved Messages topic
    /// </summary>
    Task<SavedMessagesTags> GetSavedMessagesTagsAsync(long savedMessagesTopicId = default);
}


// REUSE-IgnoreEnd