using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Returns up to 8 emoji statuses, which must be shown in the emoji status list for chats
        /// </summary>
        public class GetThemedChatEmojiStatuses : Function<EmojiStatuses>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "getThemedChatEmojiStatuses";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }


        }

        /// <summary>
        /// Returns up to 8 emoji statuses, which must be shown in the emoji status list for chats
        /// </summary>
        public static Task<EmojiStatuses> GetThemedChatEmojiStatusesAsync(
            this Client client)
        {
            return client.ExecuteAsync(new GetThemedChatEmojiStatuses
            {
                
            });
        }
    }
}
// REUSE-IgnoreEnd