using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Returns up to 8 themed emoji statuses, which color must be changed to the color of the Telegram Premium badge
        /// </summary>
        public class GetThemedEmojiStatuses : Function<EmojiStatuses>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "getThemedEmojiStatuses";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }


        }

        /// <summary>
        /// Returns up to 8 themed emoji statuses, which color must be changed to the color of the Telegram Premium badge
        /// </summary>
        public static Task<EmojiStatuses> GetThemedEmojiStatusesAsync(
            this Client client)
        {
            return client.ExecuteAsync(new GetThemedEmojiStatuses
            {
                
            });
        }
    }
}