using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TdApi
    {
        public class GetWebPageInstantView : Function<WebPageInstantView>
        {
            [JsonProperty("@type")] public override string DataType { get; set; } = "getWebPageInstantView";

            [JsonProperty("@extra")] public override string Extra { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("url")]
            public string Url { get; set; }

            [JsonConverter(typeof(Converter))]
            [JsonProperty("force_full")]
            public bool ForceFull { get; set; }
        }
    }
}