using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Adds new contacts or edits existing contacts by their phone numbers; contacts' user identifiers are ignored
        /// </summary>
        public class ImportContacts : Function<ImportedContacts>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "importContacts";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// The list of contacts to import or edit; contacts' vCard are ignored and are not imported
            /// </summary>
            [JsonProperty("contacts", ItemConverterType = typeof(Converter))]
            public Contact[] Contacts { get; set; }
        }

        /// <summary>
        /// Adds new contacts or edits existing contacts by their phone numbers; contacts' user identifiers are ignored
        /// </summary>
        public static Task<ImportedContacts> ImportContactsAsync(
            this Client client, Contact[] contacts = default)
        {
            return client.ExecuteAsync(new ImportContacts
            {
                Contacts = contacts
            });
        }
    }
}
// REUSE-IgnoreEnd