using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Invites users to an active video chat. Sends a service message of the type messageInviteVideoChatParticipants to the chat bound to the group call
        /// </summary>
        public class InviteVideoChatParticipants : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "inviteVideoChatParticipants";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Group call identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("group_call_id")]
            public int GroupCallId { get; set; }

            /// <summary>
            /// User identifiers. At most 10 users can be invited simultaneously
            /// </summary>
            [JsonProperty("user_ids", ItemConverterType = typeof(Converter))]
            public long[] UserIds { get; set; }
        }

        /// <summary>
        /// Invites users to an active video chat. Sends a service message of the type messageInviteVideoChatParticipants to the chat bound to the group call
        /// </summary>
        public static Task<Ok> InviteVideoChatParticipantsAsync(
            this Client client, int groupCallId = default, long[] userIds = default)
        {
            return client.ExecuteAsync(new InviteVideoChatParticipants
            {
                GroupCallId = groupCallId, UserIds = userIds
            });
        }
    }
}
// REUSE-IgnoreEnd