using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Reads a message on behalf of a business account; for bots only
        /// </summary>
        public class ReadBusinessMessage : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "readBusinessMessage";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Unique identifier of business connection through which the message was received
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("business_connection_id")]
            public string BusinessConnectionId { get; set; }

            /// <summary>
            /// The chat the message belongs to
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// Identifier of the message
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("message_id")]
            public long MessageId { get; set; }
        }

        /// <summary>
        /// Reads a message on behalf of a business account; for bots only
        /// </summary>
        public static Task<Ok> ReadBusinessMessageAsync(
            this Client client, string businessConnectionId = default, long chatId = default, long messageId = default)
        {
            return client.ExecuteAsync(new ReadBusinessMessage
            {
                BusinessConnectionId = businessConnectionId, ChatId = chatId, MessageId = messageId
            });
        }
    }
}
// REUSE-IgnoreEnd