using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Removes a sticker from the list of favorite stickers
        /// </summary>
        public class RemoveFavoriteSticker : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "removeFavoriteSticker";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Sticker file to delete from the list
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("sticker")]
            public InputFile Sticker { get; set; }
        }

        /// <summary>
        /// Removes a sticker from the list of favorite stickers
        /// </summary>
        public static Task<Ok> RemoveFavoriteStickerAsync(
            this Client client, InputFile sticker = default)
        {
            return client.ExecuteAsync(new RemoveFavoriteSticker
            {
                Sticker = sticker
            });
        }
    }
}
// REUSE-IgnoreEnd