using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Removes stories from an album. If the album is owned by a supergroup or a channel chat, then
        /// requires can_edit_stories administrator right in the chat. Returns the changed album
        /// </summary>
        public class RemoveStoryAlbumStories : Function<StoryAlbum>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "removeStoryAlbumStories";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the chat that owns the stories
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// Identifier of the story album
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("story_album_id")]
            public int StoryAlbumId { get; set; }

            /// <summary>
            /// Identifier of the stories to remove from the album
            /// </summary>
            [JsonProperty("story_ids", ItemConverterType = typeof(Converter))]
            public int[] StoryIds { get; set; }
        }

        /// <summary>
        /// Removes stories from an album. If the album is owned by a supergroup or a channel chat, then
        /// requires can_edit_stories administrator right in the chat. Returns the changed album
        /// </summary>
        public static Task<StoryAlbum> RemoveStoryAlbumStoriesAsync(
            this Client client, long chatId = default, int storyAlbumId = default, int[] storyIds = default)
        {
            return client.ExecuteAsync(new RemoveStoryAlbumStories
            {
                ChatId = chatId, StoryAlbumId = storyAlbumId, StoryIds = storyIds
            });
        }
    }
}
// REUSE-IgnoreEnd