using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Changes the order of chat folders
        /// </summary>
        public class ReorderChatFolders : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "reorderChatFolders";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifiers of chat folders in the new correct order
            /// </summary>
            [JsonProperty("chat_folder_ids", ItemConverterType = typeof(Converter))]
            public int[] ChatFolderIds { get; set; }

            /// <summary>
            /// Position of the main chat list among chat folders, 0-based. Can be non-zero only for Premium users
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("main_chat_list_position")]
            public int MainChatListPosition { get; set; }
        }

        /// <summary>
        /// Changes the order of chat folders
        /// </summary>
        public static Task<Ok> ReorderChatFoldersAsync(
            this Client client, int[] chatFolderIds = default, int mainChatListPosition = default)
        {
            return client.ExecuteAsync(new ReorderChatFolders
            {
                ChatFolderIds = chatFolderIds, MainChatListPosition = mainChatListPosition
            });
        }
    }
}
// REUSE-IgnoreEnd