using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Replaces the current RTMP URL for streaming to a live story; requires owner privileges for channel chats
        /// </summary>
        public class ReplaceLiveStoryRtmpUrl : Function<RtmpUrl>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "replaceLiveStoryRtmpUrl";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Chat identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }
        }

        /// <summary>
        /// Replaces the current RTMP URL for streaming to a live story; requires owner privileges for channel chats
        /// </summary>
        public static Task<RtmpUrl> ReplaceLiveStoryRtmpUrlAsync(
            this Client client, long chatId = default)
        {
            return client.ExecuteAsync(new ReplaceLiveStoryRtmpUrl
            {
                ChatId = chatId
            });
        }
    }
}
// REUSE-IgnoreEnd