using System;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class TdApi
    {
        public class RequestPasswordRecovery : Function<EmailAddressAuthenticationCodeInfo>
        {
            [JsonProperty("@type")] public override string DataType { get; set; } = "requestPasswordRecovery";

            [JsonProperty("@extra")] public override string Extra { get; set; }
        }
    }
}