using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Resends the 2-step verification recovery email address verification code
        /// </summary>
        public class ResendRecoveryEmailAddressCode : Function<PasswordState>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "resendRecoveryEmailAddressCode";

            /// <summary>
            /// Extra data attached to the message
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }
        }


        /// <summary>
        /// Resends the 2-step verification recovery email address verification code
        /// </summary>
        public static Task<PasswordState> ResendRecoveryEmailAddressCodeAsync(this Client client)
        {
            return client.ExecuteAsync(new ResendRecoveryEmailAddressCode
            {
            });
        }
    }
}