using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Searches for public channel posts using the given query. For optimal performance, the number of returned messages is chosen by TDLib and can be smaller than the specified limit
/// </summary>
public class SearchPublicPosts : Function<FoundPublicPosts>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "searchPublicPosts";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Query to search for
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("query")]
            public string Query { get; set; }

            /// <summary>
            /// Offset of the first entry to return as received from the previous request; use empty string to get the first chunk of results
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("offset")]
            public string Offset { get; set; }

            /// <summary>
            /// The maximum number of messages to be returned; up to 100. For optimal performance, the number of returned messages is chosen by TDLib and can be smaller than the specified limit
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("limit")]
            public int Limit { get; set; }

            /// <summary>
            /// The Telegram Star amount the user agreed to pay for the search; pass 0 for free searches
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("star_count")]
            public long StarCount { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public static partial class ClientExtensions
{
    /// <summary>
    /// Searches for public channel posts using the given query. For optimal performance, the number of returned messages is chosen by TDLib and can be smaller than the specified limit
    /// </summary>
    public static Task<FoundPublicPosts> SearchPublicPostsAsync(
        this Client client, string query = default, string offset = default, int limit = default, long starCount = default)
    {
        return client.ExecuteAsync(new SearchPublicPosts
        {
            Query = query, Offset = offset, Limit = limit, StarCount = starCount
        });
    }
}
public partial class Client
{
    /// <summary>
    /// Searches for public channel posts using the given query. For optimal performance, the number of returned messages is chosen by TDLib and can be smaller than the specified limit
    /// </summary>
    public Task<FoundPublicPosts> SearchPublicPostsAsync(string query = default, string offset = default, int limit = default, long starCount = default)
    {
    //test
        return ExecuteAsync(new SearchPublicPosts
        {
            Query = query, Offset = offset, Limit = limit, StarCount = starCount
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Searches for public channel posts using the given query. For optimal performance, the number of returned messages is chosen by TDLib and can be smaller than the specified limit
    /// </summary>
    Task<FoundPublicPosts> SearchPublicPostsAsync(string query = default, string offset = default, int limit = default, long starCount = default);
}


// REUSE-IgnoreEnd