using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Changes the business away message settings of the current user. Requires Telegram Business subscription
/// </summary>
public class SetBusinessAwayMessageSettings : Function<Ok>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "setBusinessAwayMessageSettings";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// The new settings for the away message of the business; pass null to disable the away message
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("away_message_settings")]
            public BusinessAwayMessageSettings AwayMessageSettings { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Changes the business away message settings of the current user. Requires Telegram Business subscription
    /// </summary>
    public Task<Ok> SetBusinessAwayMessageSettingsAsync(BusinessAwayMessageSettings awayMessageSettings = default)
    {
    //test
        return ExecuteAsync(new SetBusinessAwayMessageSettings
        {
            AwayMessageSettings = awayMessageSettings
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Changes the business away message settings of the current user. Requires Telegram Business subscription
    /// </summary>
    Task<Ok> SetBusinessAwayMessageSettingsAsync(BusinessAwayMessageSettings awayMessageSettings = default);
}


// REUSE-IgnoreEnd