using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Changes the tag or custom title of a chat member; requires can_manage_tags administrator right to change tag of other users; for basic groups and supergroups only
/// </summary>
public class SetChatMemberTag : Function<Ok>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "setChatMemberTag";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Chat identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// Identifier of the user, which tag is changed. Chats can't have member tags
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("user_id")]
            public long UserId { get; set; }

            /// <summary>
            /// The new tag of the member in the chat; 0-16 characters without emoji
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("tag")]
            public string Tag { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public static partial class ClientExtensions
{
    /// <summary>
    /// Changes the tag or custom title of a chat member; requires can_manage_tags administrator right to change tag of other users; for basic groups and supergroups only
    /// </summary>
    public static Task<Ok> SetChatMemberTagAsync(
        this Client client, long chatId = default, long userId = default, string tag = default)
    {
        return client.ExecuteAsync(new SetChatMemberTag
        {
            ChatId = chatId, UserId = userId, Tag = tag
        });
    }
}
public partial class Client
{
    /// <summary>
    /// Changes the tag or custom title of a chat member; requires can_manage_tags administrator right to change tag of other users; for basic groups and supergroups only
    /// </summary>
    public Task<Ok> SetChatMemberTagAsync(long chatId = default, long userId = default, string tag = default)
    {
    //test
        return ExecuteAsync(new SetChatMemberTag
        {
            ChatId = chatId, UserId = userId, Tag = tag
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Changes the tag or custom title of a chat member; requires can_manage_tags administrator right to change tag of other users; for basic groups and supergroups only
    /// </summary>
    Task<Ok> SetChatMemberTagAsync(long chatId = default, long userId = default, string tag = default);
}


// REUSE-IgnoreEnd