using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Changes the verification status of a user or a chat by an owned bot
        /// </summary>
        public class SetMessageSenderBotVerification : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "setMessageSenderBotVerification";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the owned bot, which will verify the user or the chat
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("bot_user_id")]
            public long BotUserId { get; set; }

            /// <summary>
            /// Identifier of the user or the supergroup or channel chat, which will be verified by the bot
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("verified_id")]
            public MessageSender VerifiedId { get; set; }

            /// <summary>
            /// Custom description of verification reason; 0-getOption("bot_verification_custom_description_length_max").
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("custom_description")]
            public string CustomDescription { get; set; }
        }

        /// <summary>
        /// Changes the verification status of a user or a chat by an owned bot
        /// </summary>
        public static Task<Ok> SetMessageSenderBotVerificationAsync(
            this Client client, long botUserId = default, MessageSender verifiedId = default, string customDescription = default)
        {
            return client.ExecuteAsync(new SetMessageSenderBotVerification
            {
                BotUserId = botUserId, VerifiedId = verifiedId, CustomDescription = customDescription
            });
        }
    }
}
// REUSE-IgnoreEnd