using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Changes the first and last name of the current user
/// </summary>
public class SetName : Function<Ok>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "setName";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// The new value of the first name for the current user; 1-64 characters
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("first_name")]
            public string FirstName { get; set; }

            /// <summary>
            /// The new value of the optional last name for the current user; 0-64 characters
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("last_name")]
            public string LastName { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Changes the first and last name of the current user
    /// </summary>
    public Task<Ok> SetNameAsync(string firstName = default, string lastName = default)
    {
    //test
        return ExecuteAsync(new SetName
        {
            FirstName = firstName, LastName = lastName
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Changes the first and last name of the current user
    /// </summary>
    Task<Ok> SetNameAsync(string firstName = default, string lastName = default);
}


// REUSE-IgnoreEnd