using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Changes a note of a contact user
        /// </summary>
        public class SetUserNote : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "setUserNote";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// User identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("user_id")]
            public long UserId { get; set; }

            /// <summary>
            /// Note to set for the user; 0-getOption("user_note_text_length_max") characters. Only Bold, Italic, Underline, Strikethrough, Spoiler, and CustomEmoji entities are allowed
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("note")]
            public FormattedText Note { get; set; }
        }

        /// <summary>
        /// Changes a note of a contact user
        /// </summary>
        public static Task<Ok> SetUserNoteAsync(
            this Client client, long userId = default, FormattedText note = default)
        {
            return client.ExecuteAsync(new SetUserNote
            {
                UserId = userId, Note = note
            });
        }
    }
}
// REUSE-IgnoreEnd