using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Sets title of a video chat; requires groupCall.can_be_managed right
        /// </summary>
        public class SetVideoChatTitle : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "setVideoChatTitle";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Group call identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("group_call_id")]
            public int GroupCallId { get; set; }

            /// <summary>
            /// New group call title; 1-64 characters
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("title")]
            public string Title { get; set; }
        }

        /// <summary>
        /// Sets title of a video chat; requires groupCall.can_be_managed right
        /// </summary>
        public static Task<Ok> SetVideoChatTitleAsync(
            this Client client, int groupCallId = default, string title = default)
        {
            return client.ExecuteAsync(new SetVideoChatTitle
            {
                GroupCallId = groupCallId, Title = title
            });
        }
    }
}
// REUSE-IgnoreEnd