using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Starts a scheduled group call
        /// </summary>
        public class StartScheduledGroupCall : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "startScheduledGroupCall";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Group call identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("group_call_id")]
            public int GroupCallId { get; set; }
        }

        /// <summary>
        /// Starts a scheduled group call
        /// </summary>
        public static Task<Ok> StartScheduledGroupCallAsync(
            this Client client, int groupCallId = default)
        {
            return client.ExecuteAsync(new StartScheduledGroupCall
            {
                GroupCallId = groupCallId
            });
        }
    }
}