using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Summarizes content of the message with non-empty summary_language_code
        /// </summary>
        public class SummarizeMessage : Function<FormattedText>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "summarizeMessage";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the chat to which the message belongs
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// Identifier of the message
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("message_id")]
            public long MessageId { get; set; }

            /// <summary>
            /// Pass a language code to which the summary will be translated; may be empty if translation isn't needed. See translateText.to_language_code for the list of supported values
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("translate_to_language_code")]
            public string TranslateToLanguageCode { get; set; }
        }

        /// <summary>
        /// Summarizes content of the message with non-empty summary_language_code
        /// </summary>
        public static Task<FormattedText> SummarizeMessageAsync(
            this Client client, long chatId = default, long messageId = default, string translateToLanguageCode = default)
        {
            return client.ExecuteAsync(new SummarizeMessage
            {
                ChatId = chatId, MessageId = messageId, TranslateToLanguageCode = translateToLanguageCode
            });
        }
    }
}
// REUSE-IgnoreEnd