using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Sends a simple network request to the Telegram servers; for testing only. Can be called before authorization
/// </summary>
public class TestNetwork : Function<Ok>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "testNetwork";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }


}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public static partial class ClientExtensions
{
    /// <summary>
    /// Sends a simple network request to the Telegram servers; for testing only. Can be called before authorization
    /// </summary>
    public static Task<Ok> TestNetworkAsync(
        this Client client)
    {
        return client.ExecuteAsync(new TestNetwork
        {
            
        });
    }
}
public partial class Client
{
    /// <summary>
    /// Sends a simple network request to the Telegram servers; for testing only. Can be called before authorization
    /// </summary>
    public Task<Ok> TestNetworkAsync()
    {
    //test
        return ExecuteAsync(new TestNetwork
        {
            
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Sends a simple network request to the Telegram servers; for testing only. Can be called before authorization
    /// </summary>
    Task<Ok> TestNetworkAsync();
}


// REUSE-IgnoreEnd