using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Allows to send unpaid messages to the given topic of the channel direct messages chat administered by the current user
/// </summary>
public class ToggleDirectMessagesChatTopicCanSendUnpaidMessages : Function<Ok>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "toggleDirectMessagesChatTopicCanSendUnpaidMessages";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Chat identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// Identifier of the topic
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("topic_id")]
            public long TopicId { get; set; }

            /// <summary>
            /// Pass true to allow unpaid messages; pass false to disallow unpaid messages
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("can_send_unpaid_messages")]
            public bool CanSendUnpaidMessages { get; set; }

            /// <summary>
            /// Pass true to refund the user previously paid messages
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("refund_payments")]
            public bool RefundPayments { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Allows to send unpaid messages to the given topic of the channel direct messages chat administered by the current user
    /// </summary>
    public Task<Ok> ToggleDirectMessagesChatTopicCanSendUnpaidMessagesAsync(long chatId = default, long topicId = default, bool canSendUnpaidMessages = default, bool refundPayments = default)
    {
    //test
        return ExecuteAsync(new ToggleDirectMessagesChatTopicCanSendUnpaidMessages
        {
            ChatId = chatId, TopicId = topicId, CanSendUnpaidMessages = canSendUnpaidMessages, RefundPayments = refundPayments
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Allows to send unpaid messages to the given topic of the channel direct messages chat administered by the current user
    /// </summary>
    Task<Ok> ToggleDirectMessagesChatTopicCanSendUnpaidMessagesAsync(long chatId = default, long topicId = default, bool canSendUnpaidMessages = default, bool refundPayments = default);
}


// REUSE-IgnoreEnd