using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Changes the ability of users to save, forward, or copy chat content. Requires owner privileges in basic groups, supergroups and channels.
        /// Requires Telegram Premium to enable protected content in private chats. Not available in Saved Messages and private chats with bots or support accounts
        /// </summary>
        public class ToggleChatHasProtectedContent : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "toggleChatHasProtectedContent";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Chat identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// New value of has_protected_content
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("has_protected_content")]
            public bool HasProtectedContent { get; set; }
        }

        /// <summary>
        /// Changes the ability of users to save, forward, or copy chat content. Requires owner privileges in basic groups, supergroups and channels.
        /// Requires Telegram Premium to enable protected content in private chats. Not available in Saved Messages and private chats with bots or support accounts
        /// </summary>
        public static Task<Ok> ToggleChatHasProtectedContentAsync(
            this IClient client, long chatId = default, bool hasProtectedContent = default)
        {
            return client.ExecuteAsync(new ToggleChatHasProtectedContent
            {
                ChatId = chatId, HasProtectedContent = hasProtectedContent
            });
        }
    }
}
// REUSE-IgnoreEnd