using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Toggles whether a topic is closed in a forum supergroup chat; requires can_manage_topics administrator right in the supergroup unless the user is creator of the topic
/// </summary>
public class ToggleForumTopicIsClosed : Function<Ok>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "toggleForumTopicIsClosed";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the chat
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }

            /// <summary>
            /// Forum topic identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("forum_topic_id")]
            public int ForumTopicId { get; set; }

            /// <summary>
            /// Pass true to close the topic; pass false to reopen it
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("is_closed")]
            public bool IsClosed { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Toggles whether a topic is closed in a forum supergroup chat; requires can_manage_topics administrator right in the supergroup unless the user is creator of the topic
    /// </summary>
    public Task<Ok> ToggleForumTopicIsClosedAsync(long chatId = default, int forumTopicId = default, bool isClosed = default)
    {
    //test
        return ExecuteAsync(new ToggleForumTopicIsClosed
        {
            ChatId = chatId, ForumTopicId = forumTopicId, IsClosed = isClosed
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Toggles whether a topic is closed in a forum supergroup chat; requires can_manage_topics administrator right in the supergroup unless the user is creator of the topic
    /// </summary>
    Task<Ok> ToggleForumTopicIsClosedAsync(long chatId = default, int forumTopicId = default, bool isClosed = default);
}


// REUSE-IgnoreEnd