using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Removes a user from the blacklist 
        /// </summary>
        public class UnblockUser : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "unblockUser";

            /// <summary>
            /// Extra data attached to the message
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// User identifier
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("user_id")]
            public int UserId { get; set; }
        }


        /// <summary>
        /// Removes a user from the blacklist 
        /// </summary>
        public static Task<Ok> UnblockUserAsync(this Client client,
            int userId = default(int))
        {
            return client.ExecuteAsync(new UnblockUser
            {
                UserId = userId,
            });
        }
    }
}