using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Creates a new supergroup from an existing basic group and sends a corresponding messageChatUpgradeTo and messageChatUpgradeFrom; requires owner privileges. Deactivates the original basic group
/// </summary>
public class UpgradeBasicGroupChatToSupergroupChat : Function<Chat>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "upgradeBasicGroupChatToSupergroupChat";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the chat to upgrade
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("chat_id")]
            public long ChatId { get; set; }
}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class Client
{
    /// <summary>
    /// Creates a new supergroup from an existing basic group and sends a corresponding messageChatUpgradeTo and messageChatUpgradeFrom; requires owner privileges. Deactivates the original basic group
    /// </summary>
    public Task<Chat> UpgradeBasicGroupChatToSupergroupChatAsync(long chatId = default)
    {
    //test
        return ExecuteAsync(new UpgradeBasicGroupChatToSupergroupChat
        {
            ChatId = chatId
        });
    }
}
public partial interface IClient
{
    /// <summary>
    /// Creates a new supergroup from an existing basic group and sends a corresponding messageChatUpgradeTo and messageChatUpgradeFrom; requires owner privileges. Deactivates the original basic group
    /// </summary>
    Task<Chat> UpgradeBasicGroupChatToSupergroupChatAsync(long chatId = default);
}


// REUSE-IgnoreEnd