using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Methods : object
    {

        public partial class answerShippingQuery : Method<Ok>
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "answerShippingQuery";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("shipping_query_id")]
                public string shipping_query_id_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("shipping_options")]
                public ShippingOption.shippingOption[] shipping_options_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("error_message")]
                public string error_message_;

        }

    }

}
