using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Methods : object
    {

        public partial class editInlineMessageReplyMarkup : Method<Ok>
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "editInlineMessageReplyMarkup";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

                [JsonConverter(typeof(Converter))]
                [JsonProperty("inline_message_id")]
                public string inline_message_id_;

                [JsonConverter(typeof(Converter))]
                [JsonProperty("reply_markup")]
                public ReplyMarkup reply_markup_;

        }

    }

}
