using System;
using Newtonsoft.Json;

namespace TD {

    /// <summary>
    /// AUTOGENERATED: DO NOT EDIT!
    /// </summary>
    public partial class Methods : object
    {

        public partial class getTermsOfService : Method<Text>
        {

                [JsonProperty("@type")]
                public override string Type { get; set; } = "getTermsOfService";

                [JsonProperty("@extra")]
                public override string Extra { get; set; }

        }

    }

}
